<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="dasg16" failures="1" tests="4" name="com.das.validation.ECommerceValidationExcell" time="167.808" errors="0" timestamp="2023-07-19T11:27:31 EDT" skipped="0">
  <testcase classname="com.das.validation.ECommerceValidationExcell" name="FillForm" time="13.780">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.das.validation.ECommerceValidationExcell.FillForm(ECommerceValidationExcell.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- FillForm -->
  <system-out>
    <![CDATA[<a href='C:\Users\goura\git\repository\AppiumFramework\Screenshots\ANDROID_Pixel6Appium\2023-07-19-11-27-15\ECommerceValidationExcell\FillForm.png'> <img src='C:\Users\goura\git\repository\AppiumFramework\Screenshots\ANDROID_Pixel6Appium\2023-07-19-11-27-15\ECommerceValidationExcell\FillForm.png' height='400' width='400'/> </a>]]>
  </system-out>
  <testcase classname="com.das.validation.ECommerceValidationExcell" name="FillForm" time="61.848"/>
  <system-out/>
  <testcase classname="com.das.validation.ECommerceValidationExcell" name="FillForm" time="32.390"/>
  <system-out/>
  <testcase classname="com.das.validation.ECommerceValidationExcell" name="FillForm" time="59.790"/>
  <system-out/>
</testsuite> <!-- com.das.validation.ECommerceValidationExcell -->
